### ISSUE TITLE
Specific resource configuration to create Mongo indexes

### ISSUE THREAD

**Issue by pfreixes** [nicolaiarocci/eve#608]
I've written a tentative commit [1] to get support for declare Mongo indexes as config of the resource and create these before the Eve application is launched. The idea is get together the schema definition and the index definition belonging to one resource. 

Next snippet shows one example of a new schema with one index defined:

```python
DOMAIN = {
    'resource': {
        'schema': {
            'name': {'type': 'string'}
        },
        'mongo_indexes': {
            'name': [('name', 1)]
        }
    }
}
```
The new `mongo_indexes` supports any kind of index already supported by [pymongo](http://api.mongodb.org/python/current/api/pymongo/collection.html) and also it supports compound indexes using various elements inside the list.

About the solution proposed. Current implementation of the data layer of Mongo, because of `pymongo_flask` extension, is highly coupled with the flask request life style and in this scenario there are two ways to figure it out. 

The first one is call at each request the properly `ensure_index` method - same for `create_index` - and get help from the already cache implemented by PyMongo driver to avoid call at last the creation function at Mongo service.

The second one, that was implemented, calls the `create_index` method before the Flask app is started,  where IMHO the index creation should be created. For this solution the current implementation of the Mongo data layer is not compatible. To overcome this situation I used the `pymongo` module and also I get some resource configuration options without use the `eve.config` module.

Feel free to comment anything about this feature and of course about the proposed implementation.

[1] https://github.com/pfreixes/eve/commit/eaacf3c059c1986741c0abe6dcf0d40c57cafaed

**Comment by nicolaiarocci** [comment]
I've always been reluctant to handle indexes at the app layer because I feel that these should be handled very carefully at (db) design stage. However, I admit that my idea was to build some sort of auto-indexing engine while your approach is very declarative, which leaves the initiative in maintainer's hands, which is cool.

On implementation: opening a temporary connection is going to be slow performance-wise, but since you provide a static method it should not be that bad. I do realise that index creation is only going to happen at startup and before the API is made available to clients, so performance might not be very relevant at this stage. 

I would experiment with moving index creation inside `register_resource` (or better, invoke creation from there), so when people register resources after startup (as we sometime do in the test suite) they still get their indexes dealt with.

Finally, I don't think you are dealing with index options at this time, and this is going to be a issue I believe. As soon as we provide an index creation option people will want to do whatever they want with them: sparse, unique, TTL, etc.

**Comment by pfreixes** [comment]
I agree with you to leave the declaration of the index coupled with the db design, but in this scenario when the user/developer already is implementing the "data schema" is necessary map also some kind of tools to install these indexes that go together with the "data schema".

Yes the current implementation using a temporary connection is a shortcut to overcome the current implementation, and it will be great if the connections made for each resource and stored to be reused by the next requests. But as you have said this lower performance is just in start up time.

Yes sure, about the register_resource I event thought about the allocation of resources in run time, let me move that. Yes right I'm not dealing with index options, let'me fix that also.

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by pfreixes** [comment]
Updated my develop branch with a new commit where the main changes adopted were:

1) Added a new optional config value to give index options i.e ```'arguments': ([('lat_long', "2d")], {"sparce": True})```
2) Catch when one already existent index has changed and remove it to create it back with the new configurations.
3) Moved the creation of the indexes upon the register_resource function.
4) Other minor stuff.

Also a specif and adhoc test suite can be coded. Currently the `create_index` method is not directly covered by any kind of test.

[1] https://github.com/pfreixes/eve/commit/de259dca30cc59686e4f8cd01aa948a14d5fad96

**Comment by pfreixes** [comment]
@nicolaiarocci sorry for the delay I was busy, I made a few changes taking into account the comments that you made.

1) Decouple create_index from the Mongo class, leaving it as isolated function without dependencies with the class
2) Removed the needs to use a ad-hoc settings config for the mongodb index feature
3) Improved the way that the test of mongodb index feature tries to find out if the indexes have been created.

[1] e813741a0a85ca40b0e864b23097e8f2b4bfd0f1

**Comment by nicolaiarocci** [comment]
Can you please submit a PR for this so, I can properly review the code and we can have eventually get feedback from others too. Thanks!

**Comment by nicolaiarocci** [comment]
Merged in https://github.com/nicolaiarocci/eve/commit/b4ed00fdb4f68d8a80d472284a59f6225ef1cb55
