### ISSUE TITLE
Minor Typo: Mongo operators has duplicate expression

### ISSUE THREAD

**Issue by slamuu** [nicolaiarocci/eve#619]
[$lt](https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/mongo.py#L74) is expressed twice

**Comment by slamuu** [comment]
Also, mongo added the [$eq](http://docs.mongodb.org/manual/reference/operator/query/eq/#eq) operator in 3.0 is there a reason for excluding that operator?

**Comment by nicolaiarocci** [comment]
Thanks for pointing that out. On the `$eq` operator, that would require some little extra work, although it is not really necessary as you can use 'and' logic already with both Eve and MongoDB. When I'll merge PyMongo 3.0 support in I'll probably add support for Mongo 3.0 operators too, although it is kind of tricky because then we would have to handle a possible failure in case an older Mongo is used..

**Comment by slamuu** [comment]
Ahh understood! Thank you for the elaboration, it was just curiosity on my part
