### ISSUE TITLE
Remove dependency on the Flask request in Mongo datalayer

### ISSUE THREAD

**Issue by amagdas** [nicolaiarocci/eve#632]
The current implementation for Mongo datalayer relies on the Flask request object being around in order to resolve the resource name: https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/mongo.py#L771
This has the obvious side effect that this is not reusable outside of a request context which is not a problem for a regular Eve app but it is if you want to actually reuse the business logic declared in the resource event handlers from a Celery worker for example.
As noted in the comment, passing the resource name down the stack is going to break the backwards compatibility for the MediaStorage but I think this is worthwhile.
Please let me know if it's ok to send a PR with these changes.

**Comment by nicolaiarocci** [comment]
I took the "let's not break things" approach there, and I knew it would cause concerns. In theory since we're still beta we're allowed to break backward compatibility and in fact we've been doing that in occasions. But people are using this thing in production everywhere so I'm hesitant. 

One approach you could take with you PR is add the parameter with a None default. If it's None then fallback to the `request` object call. This would probably not break things and still allow for an evolution of the interface. We can also make it clear both in docstrings and changelog that in a future release the dependency on Flask request object will be removed from the data layer.

**Comment by rs** [comment]
+1 for breaking backward compat in a 0.6 or 0.7 in exchange to an flask / data layer decoupling.

**Comment by amagdas** [comment]
Today or tomorrow I will create the PR for this.

**Comment by nckpark** [comment]
Also +1 for this change.

**Comment by amagdas** [comment]
Created a PR for this, feedback please.
