### ISSUE TITLE
resource validator 'unique' is restricted to the user-owned documents when auth_field is activated (on PATCH)

### ISSUE THREAD

**Issue by cyppan** [nicolaiarocci/eve#646]
My need is to makes sure my users can't modify their username (PATCH) to an already existing one. The validator works fine for POST, but on PATCH any username can be saved.

Actually the validator check [eve.io.mongo.validation.Validator._is_unique](https://github.com/nicolaiarocci/eve/blob/c264ab6e9c12ea891eca0458257ac5ad4bdc0eca/eve/io/mongo/validation.py#L101) contains:
```
if unique:
            query = {field: value}
            if self._id:
                query[config.ID_FIELD] = {'$ne': self._id}

            if app.data.find_one(self.resource, None, **query):
                self._error(field, "value '%s' is not unique" % value)
```

My resource is auth_field protected and the app.data.find_one is in my case a [`eve.io.mongo.mongo.Mongo.find_one`](https://github.com/nicolaiarocci/eve/blob/c264ab6e9c12ea891eca0458257ac5ad4bdc0eca/eve/io/mongo/mongo.py#L250) which parses / maps the query filters like this:
```
datasource, filter_, projection, _ = self._datasource_ex(
            resource,
            lookup,
            client_projection)
```
And I can see that the [_datasource_ex](https://github.com/nicolaiarocci/eve/blob/c264ab6e9c12ea891eca0458257ac5ad4bdc0eca/eve/io/base.py#L425) method injects an additional filter for auth_field on PATCH, which is not what I want, and not what someone would expect from a "unique" validator I think.
```
# Only inject the auth_field in the query when not creating new
        # documents.
        if request and request.method not in ('POST', 'PUT'):
```

I would have contribute a fix but I'm not sure what would be the fix strategy for that. I guess the app.data.find_one auth_field filter has to be there, and maybe we should switch to a more low level check in the _validate_unique method, like a `app.data.driver.db[self.resource].find_one` instead but this would maybe doesn't work with the sql alchemy data layer...?

**Comment by nicolaiarocci** [comment]
The idea is that when you use authentication filters, uniqueness is relative to the documents to which the user has access. So say you are storing invoices on a collection, you don't want the same user to store two invoices with the same number, but on the other hand two invoices can share the same number if they are from different users.

So it is actually fine to PATCH with a different username, even if it exists, since it is still unique to the user doing the operation. Of course that's not acceptable in your use case.

One dirty trick would of course be to add a unique index on the database (which probably makes sense anyway, performance-wise). This will cause an exception on PATCH, and probably a `400` returned to the client which, I concur, is probably not good enough.

One idea would be to add a new `unique_global` validation rule, then in your custom validator you could use the data driver directly as you suggested. This has the advantage that you still have the standard `unique` functionality if needed (maybe in other endpoints). A rule like this might actually be desirable for other users, so it might be worth adding support for it.

Thoughts?

**Comment by cyppan** [comment]
yes but on POST and PUT it's more like a unique_global validation which is done, not only on the user documents but on all the collection. And on PATCH the behavior is not the same so the behavior is not really consistent...

**Comment by rs** [comment]
It is also a very confusing behavior. I guess most people think about global uniqueness when they come across this Eve feature. Wouldn't it be better to have global uniqueness on the `unique` rule and add another `local_unique` (terrible name) rule for the behavior you are describing?

**Comment by nicolaiarocci** [comment]
It's true that we're being inconsistent right now. All things considered, this is my proposal:

- `unique` validates against the whole data collection (as per @cyppan request)
- `unique_touser` (better name?) is a new validation rule that validates only against user documents in the collection (you can have two fields with same value if they're stored by different users). This rule works like `unique` when/if no auth is active for the request, or if no user_auth_value has been set for the resource/request

In both cases, validation behaviour is consistent across all methods (POST, PUT, PATCH, DELETE). I have a patch which is almost ready (tests nedded), but first I wanted to hear your feedback.

**Comment by cyppan** [comment]
Sounds good to me :) maybe `unique_to_user` instead...?

**Comment by rs** [comment]
Sound great.
