### ISSUE TITLE
pre_event not called on *_internal ?

### ISSUE THREAD

**Issue by sebest** [nicolaiarocci/eve#654]
Hello,

From the code source the prevent_event are not called on *_internal methods?!

eg with POST request:
```
@pre_event
def post(resource, payl=None):
```

is it on purpose?

thanx

**Comment by rs** [comment]
I think it's a "split" error when *_internal methods have been introduced. What do you think @nicolaiarocci?

**Comment by nicolaiarocci** [comment]
Well `pre` events are intended to be raised when external requests hit the api. `_internal` methods have a different signature so some work would be required on the codebase before we can move the pre decorators down to the `_internal` methods themselves. 

Maybe you can achieve your goal by hooking callbacks to database events instead? Those are raised no matter the source of the request (internal/external).

**Comment by rs** [comment]
Sorry for the late answer. When you end up hooking a `pre` events, it's most of the time because you have no other choices, for instance when db events are happening too late.

The only fact that attached events are not triggered when request is internal is a big consistency issue. In term of implementation, why just moving the `@pre_event` on the `_internal` methods would not do the trick?
