### ISSUE TITLE
sub-resources return incorrect title

### ISSUE THREAD

**Issue by sshellabarger** [nicolaiarocci/eve#731]
I have pages setup to be a sub-resource of people.  The GET method works but returns the setting value for the title value, see below

my settings:
'url': 'people/<regex("[a-f0-9]{24}"):owner>/pages',

Results:
'title': 'people/<regex("[a-f0-9]{24}"):owner>/pages'}}

**Comment by nicolaiarocci** [comment]
Hey thanks for reporting back. Are you on 0.6?

**Comment by sshellabarger** [comment]
yes 0.6 on python 3.5

**Comment by nicolaiarocci** [comment]
Hmm from he looks of it I think you are referring to the resource title, not the actual document title. If so, you need to properly set `resource_title`, otherwise it will default to the resource url (which happens to be a regex for sub resources). Try setting `resource_title` and report back if that does not solve your issue.

**Comment by sshellabarger** [comment]
Added the resource_title and solved the issue!  Thanks.
