### ISSUE TITLE
And/Or operator in filtering

### ISSUE THREAD

**Issue by sibeliuscn** [nicolaiarocci/eve#743]
how to write a AND in a where statement ,like where={"lastname": "Doe" &"lastname": "MIKE"  }?

**Comment by pfreixes** [comment]
http://docs.mongodb.org/manual/reference/operator/query/and/
http://docs.mongodb.org/manual/reference/operator/query/or/

And then

http://python-eve.org/features.html#filtering

Have fun

**Comment by sibeliuscn** [comment]
pfreixes, 

The URLs you posted are mongo styles, I try but failed.
what i ask is how to write a AND logic in an API query .
eg,   http://myapi/endpoint?where={"lastname": "Doe" &"lastname": "MIKE" } ..
would you give me a example ?

**Comment by nicolaiarocci** [comment]
`where={"lastname": "Doe", "name": "Mike"}`

that's assuming you mean "name" as second field since you are using and ampersand in your example. With this being said, please don't use the ticket system for general how-to questions. There's Stack Overflow (eve tag) and the mailing list for that. This is reserved to bugs/feature requests and development in general.
