### ISSUE TITLE
[pymongo3] Bump pymongo and Flask-PyMongo versions

### ISSUE THREAD

**Issue by g----** [nicolaiarocci/eve#749]
Flask-Pymongo 0.4 was released few days ago. Time for updating requirements in pymongo3 branch.

**Comment by nicolaiarocci** [comment]
the `pymongo3` branch has been updated. However, there is a [bug in PyMongo 3.0+](https://jira.mongodb.org/browse/PYTHON-983) which prevents its adoption on Python 2. 

The bug is fixed in PyMongo 3.1rc0, so when 3.1 is released we will finally be able to move to PyMongo 3.0 (for the long story see https://github.com/nicolaiarocci/eve/commit/a20873528d2f3b39d5c2e675bc99e640c886ac0a)

**Comment by nicolaiarocci** [comment]
Support for PyMongo 3 has just been merged to the `develop` branch.
