### ISSUE TITLE
False datasource.projection and true soft_delete can't coexist

### ISSUE THREAD

**Issue by xgvargas** [nicolaiarocci/eve#752]
I'm migrating from 0.5.3 to 0.6.1 and also trying to use the ``soft_delete`` feature, but I think they can't be used at same time since I'm getting an error from Mongo:

`OperationFailure: database error: Can't canonicalize query: BadValue Projection cannot have a mix of inclusion and exclusion.`

I'm using the following projection to hide my password during a query. There is any other way to hide it, or a trick to have both features turned on?

 ```python
SOFT_DELETE = True
DOMAIN = {
    'accounts': {
        'embedded_fields': ['team', '_owner'],
        'datasource': {
            'projection': {'password': 0},
        },
        'schema': {
            'password': {'type': 'string', 'required': True},
            'email': {'type': 'email', 'required': True},
            .......
    },
    ........
}
```

**Comment by nicolaiarocci** [comment]
This is happening because with `soft_delete` enabled there's a default inclusive projection being activated for the `deleted` field and, as the message says, Mongo won't accept a  mix of inclusion and exclusion. The obvious question is do you really need your password to be in the resource schema since you are hiding it anyway?

**Comment by nicolaiarocci** [comment]
Ok should be fixed now! Thanks!
