### ISSUE TITLE
TRANSPARENT_SCHEMA_RULES is not disabling schema validation

### ISSUE THREAD

**Issue by ralphsmith80** [nicolaiarocci/eve#788]
This appears to be an issue with Eve post 0.5.3. I've tried the setting as described in docs and providing a custom validator with no luck. I haven't dug into this yet but it appears the the [`validate_schema`](https://github.com/nicolaiarocci/eve/blob/6d22d365915f503ad99680d5bd8c7aea84504345/eve/flaskapp.py#L360) doesn't take the `TRANSPARENT_SCHEMA_RULES` setting into account. A quick `grep` of the source makes me think it's only tested for mongo specific validations.

There's a related Eve-SQLAlchemy issue RedTurtle/eve-sqlalchemy#79.

**Comment by nicolaiarocci** [comment]
This feature has been added to 0.6.1 and only involves the Mongo default validator. Also, please see the [original pull request](https://github.com/nicolaiarocci/eve/pull/740) note on the implementation (you need to explicitly pass the `transparent_schema_rule` argument to the superclass).

**Comment by ralphsmith80** [comment]
Thanks for that info @nicolaiarocci. I took a look at that and I see, as you mentioned the `transparent_schema_rule` will only apply to the default validator for Mongo. With that in mind it would be nice to have some type of indication as to what config options pertain to Mongo and which ones are general to Eve since Eve "offers support for both MongoDB and SQL backends".

This [uniqueness of id fields](https://github.com/kynan/eve/commit/48362bc20c928ccad57fe3fad8d72f9e23412723) change seems to break the data layer encapsulation. I can't comment on the specifics for Mongo but declaring that column as `unique` in the schema is not a requirement for Postgres or SQLAlchemy, however that is the implementation currently being dictated by Eve.

As I see it we have two options to continue SQL support:
1. Require ID fields be defined as `unique` which might not play with every ones specific implementation.
2. Extend Eve itself so that the [`validate_schema`](https://github.com/nicolaiarocci/eve/blob/6d22d365915f503ad99680d5bd8c7aea84504345/eve/flaskapp.py#L360) can be overriden. That's where I see the data layer encapsulation being broken.

Just for completeness here's a very simple example of extending Eve to remove the `unique` constraint validation. I've tested this and it works but as you can see this requires both a custom data layer and the extension of Eve. Obviously this is simplistic and in production you'd probably just remove the [`unique` check](https://github.com/nicolaiarocci/eve/blob/6d22d365915f503ad99680d5bd8c7aea84504345/eve/flaskapp.py#L393-L398).
```
class EveSQL(Eve):
    def validate_schema(self, resource, schema):
        pass
        
app = EveSQL(auth=None, validator=ValidatorSQL, data=SQL)
```

What are you thoughts on this @nicolaiarocci?

**Comment by nicolaiarocci** [comment]
> With that in mind it would be nice to have some type of indication as to what config options pertain to Mongo and which ones are general to Eve since Eve "offers support for both MongoDB and SQL backends"

Good point. Eve itself is a Mongo-only shop with SQL being supported by an external extension... I guess I should make it more evident in the documentation, so people would better know where to look for what.

> This uniqueness of id fields change seems to break the data layer encapsulation. I can't comment on the specifics for Mongo but declaring that column as unique in the schema is not a requirement for Postgres or SQLAlchemy, however that is the implementation currently being dictated by Eve.

I I am not mistaken that rule was added precisely because it might be helpful for implementations/engines other than Mongo itself (which does not need it and), you know the old python saying "explicit is better than implicit". Asking @kynan opinion on this one as well.

**Comment by kynan** [comment]
I had an issue with schema validation (using Mongo) even though `transparent_schema_rules` were enabled. The reason iirc was that I had a key in the schema called `schema`, which again triggered validation of the subdictionary.

**Comment by bthorben** [comment]
@nicolaiarocci Even better would be if Eve would be mongo + SQL by development :)

**Comment by ralphsmith80** [comment]
Based on @kynan's response it appears that the unique id field was related strictly to a Mongo setup. I think adding a UNIQUE_ID_FIELD setting to skip [that check in `schema_validation`](https://github.com/nicolaiarocci/eve/blob/6d22d365915f503ad99680d5bd8c7aea84504345/eve/flaskapp.py#L394-L398) would be the most straight forward approach. 

I could make the addition via pull request, but I'll wait for @nicolaiarocci to respond with his thoughts before putting any effort towards that.

**Comment by ralphsmith80** [comment]
@bthorben I would actually be on the other end. I'd like to see Eve become an abstract framework with no backend by default. Maybe a non-persistent software layer for testing. In that case Mongo would become an extension i.e.

```
from eve import Eve
from eve_mongo import Mongo

app = Eve(data=Mongo)
app.run()
```

This would cause Eve to treat all data layers as equal and I suspect it would remove issues related to a specific data layer. Specific data layer issues would likely be an issue with the data layer extension and not Eve itself.

**Comment by nicolaiarocci** [comment]
> I'd like to see Eve become an abstract framework with no backend by default.

That's actually my long term goal. originally I wanted to release eve-mongo as a stand-alone extension with 0.6 but as can tell, it did not make it. Let's say it's coming before or along with 1.0.

**Comment by nicolaiarocci** [comment]
> I had an issue with schema validation (using Mongo) even though transparent_schema_rules were enabled. The reason iirc was that I had a key in the schema called schema, which again triggered validation of the subdictionary.

I wonder if we should keep that check in place in the first place. Mongo has unique keys by default so it is not really needed for Mongo either.

**Comment by nicolaiarocci** [comment]
> This uniqueness of id fields change seems to break the data layer encapsulation. I can't comment on the specifics for Mongo but declaring that column as unique in the schema is not a requirement for Postgres or SQLAlchemy, however that is the implementation currently being dictated by Eve.

This is interesting as Mongo does not need that check either. Actually, in mongo we are explictly removing that unique rule to avoid performance bottlenecks. 

It was my understanding that the change was introduced precisely because Eve-SQLAlchemy people needed it (@dkellner, who contributed that [commit](https://github.com/nicolaiarocci/eve/commit/48362bc20c928ccad57fe3fad8d72f9e23412723), is also a Eve-SQLAlchemy guy). If it is not needed we can simply remove it.

**Comment by dkellner** [comment]
> I'd like to see Eve become an abstract framework with no backend by default.

:+1: 

Actually, my changes handling uniqueness of id fields were introduced in this spirit. So Eve requires id fields to be unique regardless of the underlying data layer - and the latter (in case of mongo) ignores this constraint if it is not needed / redundant.

If we don't enforce this, we get really strange behaviour for custom id fields. Consider the following example:
```python
DOMAIN = {
    'books': {
        'id_field': 'isbn',
        'item_lookup_field': 'isbn',
        'item_url': 'regex("[A-Z0-9]+")',
        'schema': {
            'isbn': {'type': 'string'},
            'author': {'type': 'string'},
            'title': {'type': 'string'}
        }
    }
}
```

Without enforcing ```unique: True``` on ```isbn``` you can POST two books with the same ```isbn``` and then get them both back in a valid response via GET /books. But both items will have the same URL (_links / self / href) and therefore only one can be accessed directly.
I'm pretty sure one could avoid that constraining ```isbn``` in mongo - but if you don't do so you will get strange and imho unexpected behaviour. Tbh, I'm not really familiar with mongo, so I might be subject  to some misunderstandings here :).

-----

Somewhat off-topic: Having written that, one could look a little deeper at the interaction of id_field, item_lookup_field and uniqueness - what happens if you choose to use a different item_lookup_field than id field?

**Comment by nicolaiarocci** [comment]
Mongo would not have an issue with that as you could not store 2 identical primary keys. From this thread I gather that the same happens with SQLAlchemy. 

The solution proposed by @ralphsmith80 is good although I find kind of awkward that we'd end up adding a new setting which then would have the same value  for all data layers, since none of them really needs it. I recon that eventually it might be needed by future data layers, but to me this starts to smell and look like over-engineering. Thoughts?

**Comment by julianhille** [comment]
Code which is not needed should be removed. Keeping it in vor eventual future use is pointless. (imho)

**Comment by ralphsmith80** [comment]
> I recon that eventually it might be needed by future data layers,

In the spirit of keeping or moving Eve toward an abstract framework I would think any specific future data layer that needed that type of logic would implement it in the extensions implementation. So yea, I'm a +1 for the removal of the uniqueness check.

**Comment by nicolaiarocci** [comment]
I reverted the 'ensure uniqueness of (custom) id fields' commit. Please test it, and let me know how do you feel about this change.

**Comment by ralphsmith80** [comment]
Looks good to me. Tested and working with Eve-SQLAlchemy. Closing.
