### ISSUE TITLE
how to save money?

### ISSUE THREAD

**Issue by bhanuvrat** [nicolaiarocci/eve#791]
so I need to save financial values.
two decimal places is what I need without loss of precision.
how do people do it?

PS: pardon the misleading title.

**Comment by nicolaiarocci** [comment]
Hello, this is the Eve tickets systems used for bug reports and feature requests. For questions on how to use the tool, please use Stack Overflow (just add the `eve` tag) or the mailing list. Both have link available on the website.

With this being said, you could use python floats although they [aren't very good at arithmetic](https://docs.python.org/2/tutorial/floatingpoint.html). MongoDB/BSON does not support Decimal/Money types. What most people end up doing is store decimals as integers and convert them on (de)serialization. So in your case instead of 100,23 you would store 10023.
