### ISSUE TITLE
Hook to modify fields on POST

### ISSUE THREAD

**Issue by ddurieux** [nicolaiarocci/eve#850]
I want to modify fields in POST.

I need do this before validation of data (so hook database can't work).
I think I can with _Pre-Request Event Hook_ but lookup not get on _on_pre_POST_ so I don't know how to modify my fields easily.

If somebody has an idea, it could be cool ;)

**Comment by nicolaiarocci** [comment]
With Cerberus 1.0 (which is currently in development and is not yet supported by Eve - but it will) you will be able to transform the incoming payload, see [normalization rules](https://cerberus.readthedocs.org/en/latest/normalization-rules.html).

Until then you are out of luck, unless you build a custom validator which does pretty much what Cerb1 will do when it is ready (you can't simply use the dev branch of Cerberus right now, because it breaks Eve)

**Comment by ddurieux** [comment]
I update request.json dict and it works ;)

**Comment by nicolaiarocci** [comment]
nice one 👍
