### ISSUE TITLE
Within-one-second-precision PATCH should not raise 412

### ISSUE THREAD

**Issue by moreiramarti** [nicolaiarocci/eve#920]
Hello, 

Thanks for you API it's really cool.
I have a small question about patch requests.

I disabled conditional requests with IF-MATCH=False but when I try to send 2 patch requests within the same second, I get: 
"code": 412, "message": "Client and server etags don't match"

Maybe I'm not using it right.

Can you help me with this ?

Thanks,
Martinho MOREIRA

**Comment by marceljanerfont** [comment]
I have got the same problem. Digging in the source code I see in methods/patch.py line 174:

```
# some datetime precision magic
updates[config.LAST_UPDATED] = \
                datetime.utcnow().replace(microsecond=0)
```

They remove microseconds resolution, and if the PATCH is neutral (document is not changed) and '_updated' is not modified because you are in the same second window, therefore it returns 412, because  these lines in io/mongo/mongo.py:

```
result = coll.replace_one(filter_, changes) if replace else \
                coll.update_one(filter_, changes)
if result and result.acknowledged and result.modified_count == 0:
                raise self.OriginalChangedError()
```

A quick fix would be adding a changing field like timestamp or random value in your schema and modify it in each PATCH.

@nicolaiarocci Why do you discard microsecond precision at '_update' field?

**Comment by nicolaiarocci** [comment]
@marceljanerfont  `_update` follows the RFC1123 format which has a 1 second precision.

This looks like a bug. If `IF_MATCH` is disabled it should not return a 412, even when the second update is neutral. I'm working on a fix.

**Comment by elecay** [comment]
One thing that keeps bother me is that if I make two PATCHs in the same second without changing the document, then I will receive a 412 (this is, a **OriginalChangedError**); don't really understand why this _result.modified_count == 0_ should raise an exception. Maybe you consider that if there is no changes then the _filter__ is wrong?

**Comment by nicolaiarocci** [comment]
Hi folks, please see if the current patch solves your issues. I got it wrong the first time around, but hopefully it's fixed now.

**Comment by elecay** [comment]
Awesome Nicola! Thanks for your work and the quick response! Regards.

**Comment by marceljanerfont** [comment]
It looks fine Nicola, thanks for this awesome tool.

**Comment by nicolaiarocci** [comment]
Hi everyone. Would any of you take a look at #1231 and report their thoughts on it? I'm willing to merge it soon. Thanks.
